
  CREATE TABLE "TRAININGAPP"."USERS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(50), 
	"F_NAME" VARCHAR2(30), 
	"L_NAME" VARCHAR2(30), 
	"INACTIVE_IND" NUMBER(1,0), 
	"PROFILE_PIC" BLOB, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PROFILE_PIC") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

INSERT INTO USERS (ID, EMAIL, F_NAME, L_NAME, INACTIVE_IND, PROFILE_PIC) VALUES (1, 'test@test.com', NULL, NULL, NULL, NULL);
INSERT INTO USERS (ID, EMAIL, F_NAME, L_NAME, INACTIVE_IND, PROFILE_PIC) VALUES (22, 'test@123.com', NULL, NULL, NULL, NULL);
INSERT INTO USERS (ID, EMAIL, F_NAME, L_NAME, INACTIVE_IND, PROFILE_PIC) VALUES (21, '123@123.com', NULL, NULL, NULL, NULL);



  CREATE TABLE "TRAININGAPP"."USERS_PASS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PASS_HASH" VARCHAR2(100), 
	"REFRESH_TOKEN" VARCHAR2(200), 
	 FOREIGN KEY ("ID")
	  REFERENCES "TRAININGAPP"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO USERS_PASS (ID, PASS_HASH, REFRESH_TOKEN) VALUES (1, '$2b$10$rPxAfzh63r5Ev8TGQo9APO/PCG/zJTtw4Q8n9NBRcy7.WSN.zT0eK', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3MzM2Nzc0NjUsImV4cCI6MTczMzc2Mzg2NX0.1kA9WmobTwMgB-2FY6qVfRIBaVH0Qu_EttVsd1kbnzg');
INSERT INTO USERS_PASS (ID, PASS_HASH, REFRESH_TOKEN) VALUES (22, '$2b$10$4VeLWKyP5iKPXD47dFbCUe1Beeq80DA4Cs0w3LLS.A4nOd/rGMcri', NULL);
INSERT INTO USERS_PASS (ID, PASS_HASH, REFRESH_TOKEN) VALUES (21, '$2b$10$9AMyMejFL8v/R3KMbRKQq.4kuwLBa1HuyEotuPIsVEd3wobuL1JLC', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEyM0AxMjMuY29tIiwiaWF0IjoxNzM2NTU3MjgxLCJleHAiOjE3MzY2NDM2ODF9.XRJ6MLwj_tZRzJUV8JUGCy1Z4X6O8LwIMTC2QE5-1QI');



  CREATE TABLE "TRAININGAPP"."PLAN_COURSES" 
   (	"PLAN_COURSE_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EMP_ID" NUMBER, 
	"COURSE_ID" NUMBER, 
	"COURSEHOURS" NUMBER, 
	"TUITION" NUMBER, 
	"TRAVELHOURS" NUMBER, 
	"TRAVEL" NUMBER, 
	"CREATE_DATE" DATE, 
	"INACTIVE_IND" NUMBER(1,0), 
	"DELETE_DATE" DATE, 
	"PLAN_ID" NUMBER, 
	 PRIMARY KEY ("PLAN_COURSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;




  CREATE TABLE "TRAININGAPP"."COURSES" 
   (	"COURSEID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" NVARCHAR2(50), 
	"COURSEDESC" NVARCHAR2(250), 
	"CREATE_DATE" DATE, 
	"DELETE_DATE" DATE, 
	"INACTIVE_IND" NUMBER(1,0), 
	"TUITION" NUMBER DEFAULT 0, 
	"TRAVEL" NUMBER DEFAULT 0, 
	"COURSEHOURS" NUMBER(*,0) DEFAULT 0, 
	"TRAVELHOURS" NUMBER(*,0) DEFAULT 0, 
	 PRIMARY KEY ("COURSEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO COURSES (COURSEID, TITLE, COURSEDESC, CREATE_DATE, DELETE_DATE, INACTIVE_IND, TUITION, TRAVEL, COURSEHOURS, TRAVELHOURS) VALUES (1, 'Test', 'Testing', TO_DATE('2024-12-28 15:01:12', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-28 15:33:39', 'YYYY-MM-DD HH24:MI:SS'), 1, 10, 0, 4, 0);
INSERT INTO COURSES (COURSEID, TITLE, COURSEDESC, CREATE_DATE, DELETE_DATE, INACTIVE_IND, TUITION, TRAVEL, COURSEHOURS, TRAVELHOURS) VALUES (2, 'COMPTIA Security+', 'Comptia''s Security+ Course', TO_DATE('2024-12-28 15:31:52', 'YYYY-MM-DD HH24:MI:SS'), NULL, 0, 1200, 0, 35, 0);
INSERT INTO COURSES (COURSEID, TITLE, COURSEDESC, CREATE_DATE, DELETE_DATE, INACTIVE_IND, TUITION, TRAVEL, COURSEHOURS, TRAVELHOURS) VALUES (3, 'College Course', 'Generic 1-Semester College course', TO_DATE('2024-12-28 15:34:47', 'YYYY-MM-DD HH24:MI:SS'), NULL, 0, 1500, 0, 30, 4);
INSERT INTO COURSES (COURSEID, TITLE, COURSEDESC, CREATE_DATE, DELETE_DATE, INACTIVE_IND, TUITION, TRAVEL, COURSEHOURS, TRAVELHOURS) VALUES (5, 'Testing Long Desc', 'Testing Testing Testing Testing Testing Testing Testing Testing Testing Testing ', TO_DATE('2024-12-28 15:43:06', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-28 15:43:13', 'YYYY-MM-DD HH24:MI:SS'), 1, 100, 0, 1, 0);
INSERT INTO COURSES (COURSEID, TITLE, COURSEDESC, CREATE_DATE, DELETE_DATE, INACTIVE_IND, TUITION, TRAVEL, COURSEHOURS, TRAVELHOURS) VALUES (8, 'Testing Long Desc', 'Testing Testing Testing Testing Testing Testing Testing Testing Testing', TO_DATE('2024-12-28 18:38:25', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-28 18:39:39', 'YYYY-MM-DD HH24:MI:SS'), 1, 100, 0, 1, NULL);
INSERT INTO COURSES (COURSEID, TITLE, COURSEDESC, CREATE_DATE, DELETE_DATE, INACTIVE_IND, TUITION, TRAVEL, COURSEHOURS, TRAVELHOURS) VALUES (9, 'Testing Long Desc', 'Testing Testing Testing Testing Testing Testing Testing Testing Testing Testing Testing v', TO_DATE('2024-12-28 18:40:00', 'YYYY-MM-DD HH24:MI:SS'), NULL, 0, 100, 0, 1, 0);



  CREATE TABLE "TRAININGAPP"."PLANS" 
   (	"PLAN_ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TITLE" NVARCHAR2(50), 
	"CREATE_DATE" DATE, 
	"INACTIVE_IND" NUMBER(1,0), 
	"APPROVAL_IND" NUMBER(1,0), 
	"APPROVAL_USERID" NUMBER, 
	"DELETE_DATE" DATE, 
	"FISCAL_YEAR" NUMBER(*,0), 
	 PRIMARY KEY ("PLAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO PLANS (PLAN_ID, TITLE, CREATE_DATE, INACTIVE_IND, APPROVAL_IND, APPROVAL_USERID, DELETE_DATE, FISCAL_YEAR) VALUES (1, 'Initial 2025 Plan', TO_DATE('2024-12-28 21:55:01', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, NULL, NULL, 2025);
INSERT INTO PLANS (PLAN_ID, TITLE, CREATE_DATE, INACTIVE_IND, APPROVAL_IND, APPROVAL_USERID, DELETE_DATE, FISCAL_YEAR) VALUES (2, 'Testing Plan', TO_DATE('2024-12-29 11:21:51', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, NULL, NULL, 2025);
INSERT INTO PLANS (PLAN_ID, TITLE, CREATE_DATE, INACTIVE_IND, APPROVAL_IND, APPROVAL_USERID, DELETE_DATE, FISCAL_YEAR) VALUES (3, 'Initial 2024 Plan', TO_DATE('2024-12-29 11:24:05', 'YYYY-MM-DD HH24:MI:SS'), 0, 0, NULL, NULL, 2024);



  CREATE TABLE "TRAININGAPP"."ROLES" 
   (	"ROLE_ID" NUMBER(*,0), 
	"ROLE_DESC" VARCHAR2(100), 
	 PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO ROLES (ROLE_ID, ROLE_DESC) VALUES (1, 'USER');
INSERT INTO ROLES (ROLE_ID, ROLE_DESC) VALUES (2, 'EDITOR');
INSERT INTO ROLES (ROLE_ID, ROLE_DESC) VALUES (3, 'ADMIN');



  CREATE TABLE "TRAININGAPP"."USERS_ROLES" 
   (	"ID" NUMBER(*,0), 
	"ROLE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO USERS_ROLES (ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USERS_ROLES (ID, ROLE_ID) VALUES (22, 1);
INSERT INTO USERS_ROLES (ID, ROLE_ID) VALUES (21, 3);
INSERT INTO USERS_ROLES (ID, ROLE_ID) VALUES (21, 1);



  CREATE TABLE "TRAININGAPP"."EMPLOYEES" 
   (	"EMPID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"EFFECTIVE_PAY" NUMBER, 
	"F_NAME" VARCHAR2(50), 
	"L_NAME" VARCHAR2(50), 
	"ORG_CODE" VARCHAR2(50), 
	"INACTIVE_IND" NUMBER(1,0), 
	"DELETE_DATE" DATE, 
	"CREATE_DATE" DATE, 
	 PRIMARY KEY ("EMPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (3, 100, 'Ace', 'Clark', 'T1L1000', 0, NULL, NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (4, 10, 'Jimmy', 'Neutron', 'T1L1000', 0, NULL, NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (5, 99.99, 'LOML', 'FOREVER', 'T1L1000', 0, NULL, NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (6, 0, NULL, NULL, NULL, 1, TO_DATE('2024-12-24 09:42:08', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (7, NULL, NULL, NULL, NULL, 1, TO_DATE('2024-12-24 09:42:04', 'YYYY-MM-DD HH24:MI:SS'), NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (8, 12.12, 'Test', 'testing', 'T1L1000', 0, NULL, NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (9, 23.21, 'Jonny', 'Eio', 'T1L1000', 0, NULL, NULL);
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (10, 10.24, 'Testing1', 'Test1', 'T1L1010', 0, NULL, TO_DATE('2024-12-24 09:38:17', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO EMPLOYEES (EMPID, EFFECTIVE_PAY, F_NAME, L_NAME, ORG_CODE, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES (11, 23.24, 'Testing2', 'Test2', 'T1L1010', 0, NULL, TO_DATE('2024-12-24 09:38:17', 'YYYY-MM-DD HH24:MI:SS'));



  CREATE TABLE "TRAININGAPP"."ORGANIZATIONS" 
   (	"ORG_CODE" VARCHAR2(20), 
	"ORG_TITLE" VARCHAR2(50), 
	"ORG_DESC" VARCHAR2(200), 
	"INACTIVE_IND" NUMBER(1,0), 
	"DELETE_DATE" DATE, 
	"CREATE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

INSERT INTO ORGANIZATIONS (ORG_CODE, ORG_TITLE, ORG_DESC, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES ('T1L1030', 'Test Sub-Org #3', 'Testing Sub-Org', 1, TO_DATE('2024-12-23 16:21:34', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-23 13:44:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ORGANIZATIONS (ORG_CODE, ORG_TITLE, ORG_DESC, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES ('T1L1040', 'Test Sub-Org #4', 'Testing Sub-Org', 1, TO_DATE('2024-12-23 16:22:43', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-23 13:45:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ORGANIZATIONS (ORG_CODE, ORG_TITLE, ORG_DESC, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES ('T1L1010', 'Test Sub-Org', 'Sub-Org for Testing', 0, NULL, TO_DATE('2024-12-23 13:40:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ORGANIZATIONS (ORG_CODE, ORG_TITLE, ORG_DESC, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES ('T1L1020', 'Test Sub-Org #2', 'Testing Sub-Org', 0, NULL, TO_DATE('2024-12-23 13:41:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ORGANIZATIONS (ORG_CODE, ORG_TITLE, ORG_DESC, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES ('T1L1030', 'Test Sub-Org #3', 'Sub-Org for Testing', 0, NULL, TO_DATE('2024-12-23 16:22:24', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO ORGANIZATIONS (ORG_CODE, ORG_TITLE, ORG_DESC, INACTIVE_IND, DELETE_DATE, CREATE_DATE) VALUES ('T1L1000', 'Test Org', 'Org for testing purposes', 0, NULL, TO_DATE('2024-12-23 12:11:01', 'YYYY-MM-DD HH24:MI:SS'));


